apiVersion: v1
kind: Service
metadata:
  name: login
  namespace: qaq
spec:
  type: ClusterIP
  selector:
    app: login
  ports:
    - name: http
      port: 7777
      protocol: TCP
      targetPort: http
