// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/web/login": {
            "get": {
                "description": "Login",
                "summary": "Login",
                "responses": {
                    "302": {
                        "description": "Found"
                    }
                }
            }
        },
        "/web/login/callback": {
            "get": {
                "description": "Login",
                "summary": "LoginCallBack",
                "responses": {
                    "302": {
                        "description": "Found"
                    }
                }
            }
        },
        "/web/logout": {
            "get": {
                "description": "LoginOut",
                "summary": "LoginOut",
                "responses": {
                    "302": {
                        "description": "Found"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
