token:
  auth_exp_d: 10

rsa:
  public_key: |-
    -----BEGIN PUBLIC KEY-----
    MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC+DZt0mEOosKyrlBmWDyjxzWnr
    q9/7nh28ZWkl3bJvXZCyjEALuKOvdkOlaQQHHx8/of/AhRsf5c2+P+uC3f9EHIr/
    a++cku9Y8QwArB9w6N/inlL0S27DrbL8zxmvZdyhq83uFbhmq3z/7i3pHyYSaJou
    wEEHsD9E4J2ULcd9MwIDAQAB
    -----END PUBLIC KEY-----
  private_key: |-
    -----BEGIN RSA PRIVATE KEY-----
    MIICXAIBAAKBgQC+DZt0mEOosKyrlBmWDyjxzWnrq9/7nh28ZWkl3bJvXZCyjEAL
    uKOvdkOlaQQHHx8/of/AhRsf5c2+P+uC3f9EHIr/a++cku9Y8QwArB9w6N/inlL0
    S27DrbL8zxmvZdyhq83uFbhmq3z/7i3pHyYSaJouwEEHsD9E4J2ULcd9MwIDAQAB
    AoGBAIWPOngtqR6bSj0pzvFNphCHsrAUEUvaSjtjaQlbS1JIBq/zL+8Myrs7+T39
    Fv+KN4OYbQr2f6Fi9buFYBSPvhsBh/c0KdZk6RbYSzjs3wSQUiuicxj8TPdp1Hjh
    TOVfix//sk3qP424Yj74mImPi2z3uKawT9Y6BYEOavQq1ZPBAkEA31qbVqePBY44
    uGrnAw1AHjV4zaNWUf74y4eGfmYvlM5KG2e/V1cUsAtw767Rg3NLbdxla9rqz5i/
    vbjCx3/ZFwJBANnU9iLh/E5IYYlTlh/u63hoW2HKdNhdOpfA/d1otk8p01ifvKix
    rGKbzm8AkeTGfuyoii4qORqo8txNK0fmFkUCQCYv8qElMtHLWC1HscmWyWCg2c+m
    3opUYqtBt6ACzp3Ni2QWH+PJ8rKKsjt4kz+7Rak55mlDW6Q0xIumfD7pv+8CQGmb
    ar1crHLTep4WbRkMPxLAHVWazu06vbZm9W0LYB+fGnzD7LYodXfVK877CsBMT6qy
    x1M8WzUGpb+SliIkdbUCQF9KNhjVDmKOFi8VOYNIlSUk4tHI3upBvhFbBLciDQr8
    OyStkQ5bKNqCHkRa8duJKm8SUlnQTQA+qQmihIp9gQw=
    -----END RSA PRIVATE KEY-----

LOGIN_CLIENTID: 51d596c5372076485969
LOGIN_SECRETS: 4b2d844338151d1f85afccb749ad5076021e93db
github:
  url:
    authorize: https://github.com/login/oauth/authorize?client_id=%s&redirect_uri=%s
    accesstoken: https://github.com/login/oauth/access_token?client_id=%s&client_secret=%s&code=%s
    user: https://api.github.com/user
